// <auto-generated />
using EliminIQ_TCC.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EliminIQ_TCC.Migrations
{
    [DbContext(typeof(DbConfig))]
    partial class DbConfigModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EliminIQ_TCC.Models.Jogador", b =>
                {
                    b.Property<int>("Id_Jogador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Jogador"));

                    b.Property<string>("Email_Jogador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome_Jogador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha_Jogador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Jogador");

                    b.ToTable("Jogador");
                });

            modelBuilder.Entity("EliminIQ_TCC.Models.Quiz", b =>
                {
                    b.Property<int>("Id_Quiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Quiz"));

                    b.Property<string>("Nome_Quiz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Qtd_perguntas")
                        .HasColumnType("integer");

                    b.HasKey("Id_Quiz");

                    b.ToTable("Quiz");
                });
#pragma warning restore 612, 618
        }
    }
}
